spring:
  data:
    redis:
      port: 6379
      host: localhost
  datasource:
    url: jdbc:mysql://localhost:3306/moviedb
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true

omdb:
  apikey: 8777f47c
  api-name: omdb

themoviedb:
  apikey: 0f9dabf2ae5b87ffd0bc28efc66d4b3c
  api-name: moviedb
